package com.secretvault.app.crypto

import com.secretvault.app.core.backup.SvBackupCrypto
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.ByteBuffer
import java.nio.charset.StandardCharsets
import java.security.GeneralSecurityException
import java.util.Base64

class SvBackupCryptoTest {

    // Exact Base64 test fixture generated by Node reference implementation
    private val fixtureBase64 = "U1ZCQUNLMDEACSfAAAQAALH6fc2uiLNt4bPDxn0dNRwBAAAAAAAAAUTy+VEyuMjAaO7U0RyELAXBq2gXHp0M6t1cBw3CjOCaXPecNVr/rarOCa2oTCPsdmYZBwo7AnI8mO5mvk4Cpxz53eo/GS8GQZTUGUzlQxpKpm7vpwRfVY2oPzX35RrMj1x4XQ06PQH2gpTuzmx/eJZcPmwmsVQFBneZ6PqyvWKEh9M//in+PZUjN/Zu7agxSnWEP+79o+8aljkTOZ+XeFHBD49cQoPM5/6kq8yRxvVHEixjPcMg+mMGdwBGtjXNlJEoAtECYN4ztjdJlYNDAyPWJWPk189kGzMCuevWoUdC2/I+yjeT3sQV8uvfBSfM8JUfXZuJRoK168xCBUTCGQP3HhhxwPq+6hGjc04sjSckgMBaQVPX8DIy2+IuqBT6kG+Y49xOGtby8zlfG7MhYUjQV5EGlrbaPXSqU2sFeZTSH08p0oO0hFbhx2TWKp9ephF5wq8RAgAAAAEAAAAFL5ZV9eAyeF/gIOTkJObzkwImEvGVAwAAAAIAAAAVDyX3U2lcVSn2B3R8t7btIo1nFQSDlQECNnTbZTb1ZxcoMczWyw=="
    private val fixturePassword = "Test password — 2026"

    @Test
    fun testReferenceFixtureDecryption() {
        val archiveBytes = Base64.getDecoder().decode(fixtureBase64)
        assertTrue(archiveBytes.size > SvBackupCrypto.HEADER_SIZE)

        // 1. Verify Header
        val header = archiveBytes.copyOfRange(0, SvBackupCrypto.HEADER_SIZE)
        val salt = SvBackupCrypto.parseAndValidateHeader(header)
        assertEquals(16, salt.size)

        // 2. Derive Key
        val key = SvBackupCrypto.deriveKey(fixturePassword, salt)
        assertEquals(32, key.size)

        var offset = SvBackupCrypto.HEADER_SIZE
        var previousTag = ByteArray(SvBackupCrypto.TAG_SIZE) // 16 zeroes for record 0

        // Record 0: Manifest (Type 1)
        val rh0 = archiveBytes.copyOfRange(offset, offset + SvBackupCrypto.RECORD_HEADER_SIZE)
        offset += SvBackupCrypto.RECORD_HEADER_SIZE
        val type0 = rh0[0].toInt()
        val index0 = ByteBuffer.wrap(rh0).getInt(1)
        val length0 = ByteBuffer.wrap(rh0).getInt(5)

        assertEquals(SvBackupCrypto.TYPE_MANIFEST, type0)
        assertEquals(0, index0)

        val sealed0 = archiveBytes.copyOfRange(offset, offset + length0 + SvBackupCrypto.TAG_SIZE)
        offset += length0 + SvBackupCrypto.TAG_SIZE

        val aad0 = SvBackupCrypto.buildAad(header, rh0, previousTag)
        val plain0 = SvBackupCrypto.decryptRecord(key, index0, aad0, sealed0)
        val manifestJson = String(plain0, StandardCharsets.UTF_8)
        assertTrue(manifestJson.contains("test.jpg"))

        // Update previousTag for record 1
        previousTag = sealed0.copyOfRange(length0, length0 + SvBackupCrypto.TAG_SIZE)

        // Record 1: Media Chunk (Type 2)
        val rh1 = archiveBytes.copyOfRange(offset, offset + SvBackupCrypto.RECORD_HEADER_SIZE)
        offset += SvBackupCrypto.RECORD_HEADER_SIZE
        val type1 = rh1[0].toInt()
        val index1 = ByteBuffer.wrap(rh1).getInt(1)
        val length1 = ByteBuffer.wrap(rh1).getInt(5)

        assertEquals(SvBackupCrypto.TYPE_MEDIA_CHUNK, type1)
        assertEquals(1, index1)

        val sealed1 = archiveBytes.copyOfRange(offset, offset + length1 + SvBackupCrypto.TAG_SIZE)
        offset += length1 + SvBackupCrypto.TAG_SIZE

        val aad1 = SvBackupCrypto.buildAad(header, rh1, previousTag)
        val plain1 = SvBackupCrypto.decryptRecord(key, index1, aad1, sealed1)
        val mediaText = String(plain1, StandardCharsets.UTF_8)
        assertEquals("hello", mediaText)

        // Update previousTag for record 2
        previousTag = sealed1.copyOfRange(length1, length1 + SvBackupCrypto.TAG_SIZE)

        // Record 2: Final Summary (Type 3)
        val rh2 = archiveBytes.copyOfRange(offset, offset + SvBackupCrypto.RECORD_HEADER_SIZE)
        offset += SvBackupCrypto.RECORD_HEADER_SIZE
        val type2 = rh2[0].toInt()
        val index2 = ByteBuffer.wrap(rh2).getInt(1)
        val length2 = ByteBuffer.wrap(rh2).getInt(5)

        assertEquals(SvBackupCrypto.TYPE_FINAL_SUMMARY, type2)
        assertEquals(2, index2)

        val sealed2 = archiveBytes.copyOfRange(offset, offset + length2 + SvBackupCrypto.TAG_SIZE)
        offset += length2 + SvBackupCrypto.TAG_SIZE

        val aad2 = SvBackupCrypto.buildAad(header, rh2, previousTag)
        val plain2 = SvBackupCrypto.decryptRecord(key, index2, aad2, sealed2)
        val summaryJson = String(plain2, StandardCharsets.UTF_8)
        assertEquals("{\"items\":1,\"bytes\":5}", summaryJson)

        // True EOF check
        assertEquals(archiveBytes.size, offset)
    }

    @Test
    fun testWrongPasswordRejection() {
        val archiveBytes = Base64.getDecoder().decode(fixtureBase64)
        val header = archiveBytes.copyOfRange(0, SvBackupCrypto.HEADER_SIZE)
        val salt = SvBackupCrypto.parseAndValidateHeader(header)
        val wrongKey = SvBackupCrypto.deriveKey("wrong-password-123", salt)

        val rh0 = archiveBytes.copyOfRange(SvBackupCrypto.HEADER_SIZE, SvBackupCrypto.HEADER_SIZE + SvBackupCrypto.RECORD_HEADER_SIZE)
        val length0 = ByteBuffer.wrap(rh0).getInt(5)
        val sealed0 = archiveBytes.copyOfRange(
            SvBackupCrypto.HEADER_SIZE + SvBackupCrypto.RECORD_HEADER_SIZE,
            SvBackupCrypto.HEADER_SIZE + SvBackupCrypto.RECORD_HEADER_SIZE + length0 + SvBackupCrypto.TAG_SIZE
        )
        val aad0 = SvBackupCrypto.buildAad(header, rh0, ByteArray(SvBackupCrypto.TAG_SIZE))

        assertThrows(GeneralSecurityException::class.java) {
            SvBackupCrypto.decryptRecord(wrongKey, 0, aad0, sealed0)
        }
    }

    @Test
    fun testTamperingRejection() {
        val archiveBytes = Base64.getDecoder().decode(fixtureBase64)
        val header = archiveBytes.copyOfRange(0, SvBackupCrypto.HEADER_SIZE)
        val salt = SvBackupCrypto.parseAndValidateHeader(header)
        val key = SvBackupCrypto.deriveKey(fixturePassword, salt)

        val rh0 = archiveBytes.copyOfRange(SvBackupCrypto.HEADER_SIZE, SvBackupCrypto.HEADER_SIZE + SvBackupCrypto.RECORD_HEADER_SIZE)
        val length0 = ByteBuffer.wrap(rh0).getInt(5)
        val sealed0 = archiveBytes.copyOfRange(
            SvBackupCrypto.HEADER_SIZE + SvBackupCrypto.RECORD_HEADER_SIZE,
            SvBackupCrypto.HEADER_SIZE + SvBackupCrypto.RECORD_HEADER_SIZE + length0 + SvBackupCrypto.TAG_SIZE
        )

        // Corrupt 1 byte in ciphertext
        sealed0[0] = (sealed0[0].toInt() xor 0x01).toByte()
        val aad0 = SvBackupCrypto.buildAad(header, rh0, ByteArray(SvBackupCrypto.TAG_SIZE))

        assertThrows(GeneralSecurityException::class.java) {
            SvBackupCrypto.decryptRecord(key, 0, aad0, sealed0)
        }
    }

    @Test
    fun testInvalidHeaderMagic() {
        val badHeader = ByteArray(32) { 0 }
        assertThrows(IllegalArgumentException::class.java) {
            SvBackupCrypto.parseAndValidateHeader(badHeader)
        }
    }

    @Test
    fun testInvalidHeaderIterations() {
        val header = ByteBuffer.allocate(32)
            .put(SvBackupCrypto.MAGIC)
            .putInt(100000) // Wrong iterations
            .putInt(SvBackupCrypto.CHUNK_SIZE)
            .put(ByteArray(16))
            .array()

        assertThrows(IllegalArgumentException::class.java) {
            SvBackupCrypto.parseAndValidateHeader(header)
        }
    }

    @Test
    fun testInvalidHeaderChunkSize() {
        val header = ByteBuffer.allocate(32)
            .put(SvBackupCrypto.MAGIC)
            .putInt(SvBackupCrypto.EXPECTED_ITERATIONS)
            .putInt(65536) // Wrong chunk size
            .put(ByteArray(16))
            .array()

        assertThrows(IllegalArgumentException::class.java) {
            SvBackupCrypto.parseAndValidateHeader(header)
        }
    }

    @OptIn(ExperimentalStdlibApi::class)
    @Test
    fun testPbkdf2NodeReferenceVectors() {
        val salt = "0102030405060708090a0b0c0d0e0f10".hexToByteArray()

        val vectors = listOf(
            "password" to "ad616228b5f1837ec1fa8a1d14833db28d5e7c841617736055a07c02f3afbe2e",
            "Separate backup password — 2026" to "902b6fb1e2afa64c36c190ba824b407e2b78628d6aafab700c1206c1e74760c3",
            "  spaces  before and after  " to "9c21ce16151fa44b7b79177c842814ad79ed8f39f41bc32eb6c2816e15c271fc",
            "Accented: éàçüöñ" to "9cd437683b5059b80564512f21a9befd11d8311c2bc1e29c2e575bea47c611a5",
            "Emoji: 🔒🔑🛡️" to "40c9670c99ae6f3cd69b4a6cdc971eeff92ff407afb88dac4a4c7f25ec4ac1d0",
            "A".repeat(1024) to "0b85b5d897da9330dac25c6dae3faa36c9955f9c03130ab104af09e8a5b2d9df"
        )

        for ((pass, expectedHex) in vectors) {
            val key = SvBackupCrypto.deriveKey(pass, salt)
            assertEquals("Mismatch for password: $pass", expectedHex, key.toHexString())
        }
    }
}
